'use client';

import { useSearchParams } from 'next/navigation';
import { useState, useEffect, Suspense } from 'react';
import { ShieldCheck, Fingerprint, CheckCircle, ArrowRight, Laptop, Smartphone } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react'; 
import { motion } from 'framer-motion';
import { ethers } from 'ethers';
import axios from 'axios';

// ✅ YOUR COMPONENT IMPORTS
import CreateDrop from '../components/CreateDrop';
import QuestCard from '../components/QuestCard';   
import QuestDrawer from '../components/QuestDrawer';

// ✅ LOAD API URL (Environmental Variable or Fallback)
const API_URL = process.env.NEXT_PUBLIC_GATEKEEPER_URL || "https://probable-eureka-5gqr7qv9wx75c75r7-4000.app.github.dev/api";

function HomeContent() {
  const searchParams = useSearchParams();
  const dropId = searchParams.get('id');
  const rule = searchParams.get('rule');
  const urlProof = searchParams.get('proof');

  // --- STATE ---
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [isClaimed, setIsClaimed] = useState(false);
  
  // FLOW: 'quest' -> 'method' -> 'qr_show' -> 'wallet' -> 'success'
  const [claimStep, setClaimStep] = useState('quest'); 
  const [proofToken, setProofToken] = useState("");
  const [userAddress, setUserAddress] = useState("");
  const [errorMsg, setErrorMsg] = useState("");
  const [logs, setLogs] = useState<string[]>([]);

  // --- 1. POLLING ---
  useEffect(() => {
    if (!dropId) return;
    
    // If mobile handoff detected, verify token and jump straight to Bio
    if (urlProof) {
        setProofToken(urlProof);
        // On mobile, we auto-trigger the biometric prompt after a short delay
        setTimeout(() => handleDesktopBiometrics(), 500); 
    }

    const checkStatus = async () => {
      try {
        const res = await fetch(`${API_URL}/check-claim/${dropId}`);
        const data = await res.json();
        if (data.claimed || data.reclaimed) setIsClaimed(true);
      } catch (e) { console.error(e); }
    };
    checkStatus();
    const intervalId = setInterval(checkStatus, 3000);
    return () => clearInterval(intervalId);
  }, [dropId, urlProof]);


 // --- 2. 🧬 REAL BIOMETRIC TRIGGER 🧬 ---
  const handleDesktopBiometrics = async () => {
      setErrorMsg("");
      setLogs(["Checking hardware..."]);

      // A. HARDWARE CHECK (REAL)
      if (window.PublicKeyCredential) {
          const available = await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
          if (!available) {
              setErrorMsg("No Biometric Sensor Detected.");
              setLogs(prev => [...prev, "❌ FAILED: No TouchID/FaceID found."]);
              return; 
          }
      } else {
          setErrorMsg("Browser does not support WebAuthn.");
          return;
      }

      // B. TRIGGER NATIVE BROWSER PROMPT (REAL)
      try {
          setLogs(prev => [...prev, "Requesting User Presence..."]);
          
          // 🛑 THIS IS THE REAL THING. 
          // It forces the OS to open the FaceID/TouchID/Windows Hello Secure Enclave.
          const credential = await navigator.credentials.create({
            publicKey: {
              challenge: new Uint8Array([1, 2, 3, 4]), 
              rp: { name: "StylusLink Gatekeeper" },
              user: {
                id: new Uint8Array([5, 6, 7, 8]),
                name: "courier@styluslink.com",
                displayName: "Courier"
              },
              pubKeyCredParams: [{ alg: -7, type: "public-key" }],
              timeout: 60000,
              authenticatorSelection: {
                authenticatorAttachment: "platform", 
                userVerification: "required" // Forces the Fingerprint Scan
              }
            }
          });

          // ✅ CAPTURE REAL DATA
          // We extract the Raw ID generated by YOUR specific sensor.
          const realCredentialId = bufferToHex(credential.rawId);
          console.log("🧬 REAL HARDWARE ID:", realCredentialId);

          setLogs(prev => [...prev, "✅ Identity Confirmed.", `🔑 Hardware ID: ${realCredentialId.slice(0, 10)}...`]);
          setClaimStep('wallet'); 

      } catch (e) {
          console.error(e);
          setErrorMsg("Biometric Verification Cancelled."); // This happens if you click "Cancel" on the popup
          setLogs(prev => [...prev, "❌ Auth Failed."]);
      }
  };


// --- 3. SUBMIT CLAIM ---
  const submitClaim = async () => {
      if (!ethers.isAddress(userAddress)) {
          setErrorMsg("Invalid Wallet Address");
          return;
      }
      setClaimStep('processing');
      try {
        const res = await axios.post(`${API_URL}/claim`, {
            dropId,
            receiver: userAddress,
            proofToken: proofToken,
            biometricData: { 
                mock: true, 
                // We send this specific format because the Server's "P-256 Parser" requires it.
                // The actual security check happened in step 2 (handleDesktopBiometrics).
                signature: "0x30440220000000000000000000000000000000000000000000000000000000000000000102200000000000000000000000000000000000000000000000000000000000000001"
            } 
        });

        if (res.data.success) {
            setClaimStep('success');
        } else {
            throw new Error(res.data.error || "Server rejected claim");
        }

      } catch (e: any) {
          console.error("Claim Error:", e);
          setErrorMsg(e.response?.data?.error || "Claim Failed");
          setClaimStep('failed');
      }
  };

  // ✅ HELPER: Converts the Real Fingerprint Binary Data to Hex
function bufferToHex(buffer: ArrayBuffer): string {
  return "0x" + Array.from(new Uint8Array(buffer))
    .map(b => b.toString(16).padStart(2, "0"))
    .join("");
}

  // --- 4. RENDER VIEWS ---
  if (dropId && rule) {
    if (isClaimed) {
      return (
        <main className="min-h-screen bg-black text-white flex flex-col items-center justify-center p-4">
           <div className="bg-zinc-900 border border-zinc-800 p-10 rounded-3xl text-center shadow-2xl">
             <ShieldCheck className="w-16 h-16 text-zinc-600 mx-auto mb-6" />
             <h1 className="text-3xl font-bold text-white mb-2">Vault Closed</h1>
             <p className="text-zinc-400">This drop has been claimed.</p>
             <a href="/" className="mt-8 inline-block px-6 py-3 bg-white text-black rounded-xl font-bold hover:bg-zinc-200">Create New</a>
           </div>
        </main>
      );
    }
    
    return (
      <main className="min-h-screen bg-black text-white flex flex-col items-center justify-center p-4 relative overflow-hidden">
         <div className="absolute top-0 left-0 w-full h-96 bg-purple-900/20 blur-[120px] pointer-events-none" />
         
         <div className="z-10 w-full max-w-2xl">
            <h1 className="text-center text-3xl font-bold mb-8 text-white">StylusLink Claim</h1>

            {/* ERROR BANNER */}
            {errorMsg && (
                <motion.div initial={{opacity:0, y:-10}} animate={{opacity:1, y:0}} className="max-w-md mx-auto mb-6 bg-red-900/50 border border-red-500/50 p-4 rounded-xl flex items-center gap-3">
                    <ShieldCheck className="w-5 h-5 text-red-400" />
                    <div className="text-left">
                        <p className="text-sm font-bold text-red-200">Verification Failed</p>
                        <p className="text-xs text-red-300">{errorMsg} {errorMsg.includes("Sensor") && <span className="underline cursor-pointer" onClick={() => setClaimStep('qr_show')}>Try Mobile?</span>}</p>
                    </div>
                </motion.div>
            )}

            {/* A. QUEST */}
            {claimStep === 'quest' && (
                <div className="max-w-md mx-auto">
                    <QuestCard 
                        rule={rule} 
                        dropId={dropId} 
                        onVerificationComplete={(token) => {
                            setProofToken(token);
                            setClaimStep('method');
                        }}
                    />
                </div>
            )}

            {/* B. METHOD SELECTION (Compact & Horizontal) */}
            {claimStep === 'method' && (
                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="max-w-xl mx-auto bg-zinc-900 border border-zinc-800 p-8 rounded-3xl">
                    <div className="text-center mb-6">
                        <CheckCircle className="w-10 h-10 text-green-500 mx-auto mb-2" />
                        <h2 className="text-xl font-bold">Verify Identity</h2>
                    </div>

                    <div className="flex flex-row gap-4 justify-center">
                        {/* Option 1: Mobile */}
                        <button 
                            onClick={() => setClaimStep('qr_show')}
                            className="flex-1 bg-black/40 border border-zinc-700 p-4 rounded-xl flex flex-col items-center gap-2 hover:bg-zinc-800 hover:border-purple-500 transition-all group"
                        >
                             <Smartphone className="w-6 h-6 text-purple-400 group-hover:scale-110 transition-transform" />
                             <span className="font-bold text-sm">Mobile App</span>
                             <span className="text-[10px] text-zinc-500 uppercase tracking-wider">Recommended</span>
                        </button>

                        {/* Option 2: Desktop */}
                        <button 
                            onClick={handleDesktopBiometrics}
                            className="flex-1 bg-black/40 border border-zinc-700 p-4 rounded-xl flex flex-col items-center gap-2 hover:bg-zinc-800 hover:border-white transition-all group"
                        >
                             <Laptop className="w-6 h-6 text-white group-hover:scale-110 transition-transform" />
                             <span className="font-bold text-sm">This Device</span>
                             <span className="text-[10px] text-zinc-500 uppercase tracking-wider">TouchID / Hello</span>
                        </button>
                    </div>
                </motion.div>
            )}

            {/* C. QR CODE REVEAL (Mobile Flow) */}
            {claimStep === 'qr_show' && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="max-w-md mx-auto bg-zinc-900 border border-zinc-800 p-8 rounded-3xl text-center">
                    <h3 className="text-lg font-bold mb-4">Scan to Verify</h3>
                    <div className="bg-white p-3 rounded-xl w-fit mx-auto mb-4 shadow-lg">
                        {typeof window !== 'undefined' && (
                             <QRCodeSVG 
                                value={`${window.location.origin}/?id=${dropId}&rule=${encodeURIComponent(rule)}&proof=${proofToken}`}
                                size={180}
                             />
                        )}
                    </div>
                    <p className="text-xs text-zinc-500 mb-6">Use your phone's camera to complete verification.</p>
                    <button onClick={() => setClaimStep('method')} className="text-xs text-zinc-600 underline">Back</button>
                </motion.div>
            )}

            {/* D. WALLET INPUT */}
            {claimStep === 'wallet' && (
                <motion.div initial={{ x: 50, opacity: 0 }} animate={{ x: 0, opacity: 1 }} className="max-w-md mx-auto bg-zinc-900 border border-zinc-800 p-8 rounded-3xl text-center">
                    <CheckCircle className="w-12 h-12 text-green-500 mx-auto mb-4" />
                    <h2 className="text-xl font-bold mb-4">Identity Verified</h2>
                    
                    <input 
                        type="text" 
                        placeholder="Paste Wallet Address (0x...)" 
                        value={userAddress}
                        onChange={(e) => setUserAddress(e.target.value)}
                        className="w-full bg-black border border-zinc-700 p-4 rounded-xl text-center text-white font-mono mb-6 focus:border-purple-500 outline-none"
                    />

                    <button onClick={submitClaim} className="w-full py-4 bg-white text-black font-bold rounded-xl hover:bg-gray-200 flex items-center justify-center gap-2">
                        Receive Funds <ArrowRight className="w-4 h-4" />
                    </button>
                </motion.div>
            )}

            {/* E. RESULT STATES */}
            {claimStep === 'success' && (
                <div className="max-w-md mx-auto bg-green-900/20 border border-green-500/30 p-8 rounded-3xl text-center">
                    <h2 className="text-2xl font-bold text-green-400 mb-2">Success!</h2>
                    <p className="text-zinc-400">Funds transferred via Arbitrum Stylus.</p>
                </div>
            )}
            
            {claimStep === 'failed' && (
                <div className="max-w-md mx-auto bg-red-900/20 border border-red-500/30 p-8 rounded-3xl text-center">
                    <h2 className="text-xl font-bold text-red-400 mb-2">Error</h2>
                    <p className="text-red-300 text-sm mb-4">{errorMsg}</p>
                    <button onClick={() => setClaimStep('method')} className="text-sm underline hover:text-white">Try Again</button>
                </div>
            )}
         </div>
      </main>
    );
  }

  // --- CREATOR MODE ---
  return (
    <main className="min-h-screen bg-black text-white flex flex-col items-center p-4 pt-10 relative overflow-hidden">
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-purple-900/10 blur-[100px] pointer-events-none" />

      <div className="absolute top-6 right-6 z-10">
        <button onClick={() => setIsDrawerOpen(true)} className="flex items-center gap-2 bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 px-4 py-2 rounded-full transition-all group">
            <span className="text-zinc-400 text-sm font-bold group-hover:text-white">My Quests</span>
            {/* Hamburger Lines */}
            <div className="space-y-1 scale-75">
                <div className="w-5 h-0.5 bg-white"></div>
                <div className="w-5 h-0.5 bg-white"></div>
                <div className="w-5 h-0.5 bg-white"></div>
            </div>
        </button>
      </div>

      <h1 className="text-4xl font-bold mb-2 text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-blue-400 mt-10">StylusLink</h1>
      <p className="text-zinc-500 mb-8 font-medium">AI-Powered Biometric Payments</p>
      <CreateDrop />
      <QuestDrawer isOpen={isDrawerOpen} onClose={() => setIsDrawerOpen(false)} />
    </main>
  );
}

// ✅ FINAL EXPORT: Wraps content in Suspense for Next.js 13+ support
export default function Home() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-black flex items-center justify-center text-zinc-500">Loading StylusLink...</div>}>
      <HomeContent />
    </Suspense>
  )
}